src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/ImageCard/ImageCardViewComponent.cs
using CollectIt.Database.Entities.Resources;
using CollectIt.MVC.View.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.ImageCard;

public class ImageCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ImageViewModel image)
    {
        return View(image);
    }
} 

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/ImageCards/ImageCardsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.ImageCards;

public class ImageCardsViewComponent : ViewComponent
{
    public ImageCardsViewComponent()
    { }

    public IViewComponentResult Invoke()
    {
        return View();
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/MusicCard/MusicCardViewComponent.cs
using CollectIt.Database.Entities.Resources;
using CollectIt.MVC.View.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.MusicCard;

public class MusicCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(MusicViewModel music)
    {
        return View(music);
    }
} 

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/MusicCards/ImageCardsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.MusicCards;

public class MusicCardsViewComponent : ViewComponent
{
    public MusicCardsViewComponent()
    { }

    public IViewComponentResult Invoke()
    {
        return View();
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/SearchBar/SearchBarViewComponent.cs
using CollectIt.Database.Entities.Account;
using CollectIt.MVC.View.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.SearchBar;

[ViewComponent(Name = "SearchBar")]
public class SearchBarViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(string? action = null,
                                       string? controller = null,
                                       string? query = null,
                                       ResourceType chosenType = ResourceType.Image)
    {
        var type = controller switch
                   {
                       "Musics" => ResourceType.Music,
                       "Videos" => ResourceType.Video,
                       _        => ResourceType.Image
                   };
        return View(new SearchBarViewModel()
                    {
                        Action = action ?? "Index",
                        Controller = controller ?? "Home",
                        Query = query ?? string.Empty,
                        ResourceType = type
                    });
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/SubscriptionCard/SubscriptionCardViewComponent.cs
using CollectIt.Database.Entities.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments;

namespace CollectIt.MVC.View.Views.Shared.Components.SubscriptionCard;

public class SubscriptionCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(Subscription subscription)
    {
        return View(subscription);
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/SubscriptionCards/SubscriptionCardsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.SubscriptionCards;


public class SubscriptionCardsViewComponent : ViewComponent
{
    public SubscriptionCardsViewComponent()
    { }
    
    public IViewComponentResult Invoke(SubscriptionCardsViewModel model)
    {
        return View(model);
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/VideoCard/VideoCardViewComponent.cs
using CollectIt.Database.Entities.Resources;
using CollectIt.MVC.View.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.VideoCard;

public class VideoCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(VideoViewModel video)
    {
        return View(video);
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/VideoCards/VideoCardsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CollectIt.MVC.View.Views.Shared.Components.VideoCards;

public class VideoCardsViewComponent : ViewComponent
{
    public VideoCardsViewComponent()
    { }

    public IViewComponentResult Invoke()
    {
        return View();
    }
}

src/collect-it/src/CollectIt.MVC/CollectIt.MVC.View/Views/Shared/Components/ImageCards/Default.cshtml
@using CollectIt.MVC.View.ViewModels
@using CollectIt.MVC.View.Views.Shared.Components.ImageCard
@model CollectIt.MVC.View.Views.Shared.Components.ImageCards.ImageCardsViewModel
@{
    var k = Model.Images.Count / 3;
    var g = Model.Images.Count % 3;
}

<div class="images">
    @for (var i = 0; i < 3; i++)
    {
        var temp = new List<ImageViewModel>();
        if (i * k < Model.Images.Count)
        {
            if (i != 1)
            {
                temp = g switch
                       {
                       1 => i == 0
                                ? Model.Images.ToList().GetRange(0, k)
                                : Model.Images.Skip(i * k + 1).ToList(),
                       2 => i == 0
                                ? Model.Images.ToList().GetRange(0, k + 1)
                                : Model.Images.Skip(i * k + 1).ToList(),
                       _ => Model.Images.Skip(i * k).ToList().GetRange(0, k)
                       };
            }
            else
            {
                temp = g switch
                       {
                       1 => Model.Images.Skip(k).ToList().GetRange(0, k + 1),
                       2 => Model.Images.Skip(k + 1).ToList().GetRange(0, k),
                       _ => Model.Images.Skip(k).ToList().GetRange(0, k)
                       };
            }
        }


        <div class="resources-box">
            @foreach (var image in temp)
            {
                <vc:image-card image="@image"/>
            }
        </div>
    }
</div>
    